# Hadolint configuration for VinylDigger Dockerfiles
# https://github.com/hadolint/hadolint

# Ignored rules with explanations
ignored:
  # DL3008: Pin versions in apt get install
  # We use latest versions from the base image's repository for security updates
  - DL3008

  # DL3018: Pin versions in apk add
  # We use latest versions from Alpine's repository for security updates
  - DL3018

  # SC2016: Single quotes don't expand variables
  # We intentionally use single quotes in some contexts
  - SC2016

# Trusted registries for FROM instructions
trustedRegistries:
  - docker.io
  - ghcr.io
