# Hadolint configuration for VinylDigger Dockerfiles
# https://github.com/hadolint/hadolint

# Ignored rules with explanations
ignored:
  # DL3008: Pin versions in apt get install
  # We use latest versions from the base image's repository for security updates
  - DL3008

  # DL3018: Pin versions in apk add
  # We use latest versions from Alpine's repository for security updates
  - DL3018

  # SC2016: Single quotes don't expand variables
  # We intentionally use single quotes in some contexts
  - SC2016

# Trusted registries for FROM instructions
trustedRegistries:
  - docker.io
  - ghcr.io

# Enforce strict labeling - warn against labels not in schema
strict-labels: true

# Required OCI standard labels for container metadata
# Based on https://github.com/opencontainers/image-spec/blob/main/annotations.md
# Note: Using 'text' for version and revision since they use build-time variables
label-schema:
  org.opencontainers.image.created: text
  org.opencontainers.image.title: text
  org.opencontainers.image.description: text
  org.opencontainers.image.authors: text
  org.opencontainers.image.vendor: text
  org.opencontainers.image.version: text
  org.opencontainers.image.revision: text
  org.opencontainers.image.source: url
  org.opencontainers.image.documentation: url
  org.opencontainers.image.licenses: text
  org.opencontainers.image.base.name: text
