repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 0b19ef1fd6ad680ed7752d6daba883ce1265a6de  # frozen: v0.12.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 0f86793af5ef5f6dc63c8d04a3cabfa3ea8f9c6a  # frozen: v1.16.1
    hooks:
      - id: mypy
        files: ^backend/
        additional_dependencies:
          - types-redis
          - types-requests
          - sqlalchemy[mypy]

  - repo: https://github.com/hadolint/hadolint
    rev: c3dc18df7a501f02a560a2cc7ba3c69a85ca01d3  # frozen: v2.13.1-beta
    hooks:
      - id: hadolint-docker

  - repo: local
    hooks:
      - id: frontend-eslint
        name: Frontend ESLint
        entry: sh -c 'cd frontend && npm run lint'
        language: system
        files: ^frontend/.*\.[jt]sx?$
        pass_filenames: false
        always_run: false
        require_serial: true

  - repo: local
    hooks:
      - id: frontend-typecheck
        name: Frontend TypeScript Check
        entry: sh -c 'cd frontend && npm run typecheck'
        language: system
        files: ^frontend/.*\.[jt]sx?$
        pass_filenames: false
        always_run: false
        require_serial: true

  - repo: https://github.com/commitizen-tools/commitizen
    rev: c710c9f541ae452547fdce5c360929f007ec4867  # frozen: v4.8.3
    hooks:
      - id: commitizen
        stages: [commit-msg]
